// <auto-generated />
using System;
using Gestion_de_Bibliothéque.datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_de_Bibliothéque.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20250116113307_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Gestion_de_Bibliothéque.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PubDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Mariama Ba",
                            PubDate = new DateOnly(2000, 10, 29),
                            Title = "sous l'orage"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Mariama Ba",
                            PubDate = new DateOnly(2000, 10, 29),
                            Title = "sous l'orage"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
